//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    pub recipient: Option<Uuid>,
    pub origin_map_point: Option<Uuid>,
    pub destination_map_point: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::map_point::Entity",
        from = "Column::DestinationMapPoint",
        to = "super::map_point::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MapPoint2,
    #[sea_orm(
        belongs_to = "super::map_point::Entity",
        from = "Column::OriginMapPoint",
        to = "super::map_point::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MapPoint1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Recipient",
        to = "super::users::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
