//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod clients;
pub mod deliveries;
pub mod invitations;
pub mod location;
pub mod location_kind;
pub mod map_point;
pub mod merchant;
pub mod merchant_invitations;
pub mod poem_sessions;
pub mod profiles;
pub mod roles;
pub mod user_roles;
pub mod users;
